name: "CI"
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format
      - name: Check format
        run: git diff --exit-code
      - name: Build
        run: yarn build
      - name: Checked in build?
        run: git diff --exit-code
      - name: Test
        uses: ./
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
